service: chewbacca-object-detection

frameworkVersion: '2 || 3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: '20201221'
  stage: dev
  region: us-west-2

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
    fileSystemConfig:
      arn: arn:aws:elasticfilesystem:us-west-2:282903050140:access-point/fsap-0dec985852c543764
      localMountPath: /mnt/tapod
    vpc:
      securityGroupIds:
        - sg-bb367ec7
      subnetIds:
        - subnet-fb9e9d9d
        - subnet-3111d71a
        - subnet-ec2507a4
        - subnet-3706f96d

plugins:
  - serverless-wsgi
  - serverless-python-requirements
